package org.launchcode.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Created by LaunchCode
 */
@Entity
//gave it entity annotation
//made sure it had an id field that is generated by the spring data layer
public class Cheese {

    @Id//annotation tells hibernate that this is the primary key
    @GeneratedValue//flags hibernate to tell it to generate a value for us
    private int id;

    @NotNull
    @Size(min=3, max=15)
    private String name;
    /**
     * @OneToMany
     * @JoinColumn(name = "category_id")
     *private List<Cheese> cheeses = new ArrayList<>();
     *
     *@ManyToOne
     * private Category category;
     *
     * public Cheese(String name, String description) {
     *     this.name = name;
     *     this.description = description;
     * }
     */
    @NotNull
    @Size(min=1, message = "Description must not be empty")
    private String description;

    private CheeseType type;

    public Cheese(String name, String description) {
        this.name = name;
        this.description = description;
    }

    public Cheese() { }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public CheeseType getType() {
        return type;
    }

    public void setType(CheeseType type) {
        this.type = type;
    }
}
